#pragma once

#include "define.hpp"

// L1-6 R1-6
uint8_t keyAssign[][KEY_ASSIGN_NUM] = {
    {INPUT_BLAST, INPUT_TRG_B, INPUT_TRG_A, INPUT_R1, INPUT_L1, INPUT_NOP,
     INPUT_DOWN, INPUT_LEFT, INPUT_UP, INPUT_RIGHT, INPUT_NOP, INPUT_DOWN,
     INPUT_SELECT, INPUT_START, INPUT_MODE_Z},
    {INPUT_DOWN, INPUT_RIGHT, INPUT_UP, INPUT_LEFT, INPUT_NOP, INPUT_DOWN,
     INPUT_BLAST, INPUT_TRG_B, INPUT_TRG_A, INPUT_L1, INPUT_R1, INPUT_NOP,
     INPUT_SELECT, INPUT_START, INPUT_MODE_Z},
    {INPUT_TRG_C, INPUT_TRG_B, INPUT_TRG_A, INPUT_R1, INPUT_L1, INPUT_NOP,
     INPUT_DOWN, INPUT_LEFT, INPUT_UP, INPUT_RIGHT, INPUT_NOP, INPUT_DOWN,
     INPUT_SELECT, INPUT_START, INPUT_MODE_W},
    {INPUT_DOWN, INPUT_RIGHT, INPUT_UP, INPUT_LEFT, INPUT_NOP, INPUT_DOWN,
     INPUT_TRG_C, INPUT_TRG_B, INPUT_TRG_A, INPUT_L1, INPUT_R1, INPUT_NOP,
     INPUT_SELECT, INPUT_START, INPUT_MODE_W},
    {INPUT_TRG_C, INPUT_TRG_B, INPUT_TRG_A, INPUT_R1, INPUT_L1, INPUT_03,
     INPUT_DOWN, INPUT_LEFT, INPUT_UP, INPUT_RIGHT, INPUT_07, INPUT_DOWN,
     INPUT_SELECT, INPUT_START, INPUT_MODE_W},
};
